# You can add additional endpoints to this list as needed.

ENDPOINTS_LIST = [
    "/products",
    "/products/{arg_1}",
    "/products/{arg_1}/variants",
    "/products/{arg_1}/variants/{arg_2}",
    "/products/{arg_1}/variants/{arg_2}/custom_fields",
    "/products/{arg_1}/images",
    "/products/{arg_1}/images/{arg_2}",
    "/products/{arg_1}/custom_fields",
    "/products/{arg_1}/custom_fields/{arg_2}",
    "/orders",
    "/orders/{arg_1}",
    "/orders/{arg_1}/custom_fields",
    "/orders/{arg_1}/open",
    "/orders/{arg_1}/close",
    "/orders/{arg_1}/cancel",
    "/orders/{arg_1}/pack",
    "/orders/{arg_1}/fulfill",
    "/customers",
    "/customers/{arg_1}",
    "/customers/{arg_1}/custom_fields",
    "/carts",
    "/carts/{arg_1}",
    "/categories",
    "/categories/{arg_1}",
    "/categories/{arg_1}/custom_fields",
    "/coupons",
    "/coupons/{arg_1}",
    "/discounts",
    "/discounts/{arg_1}",
    "/metafields",
    "/metafields/{arg_1}",
    "/draft_orders",
    "/draft_orders/{arg_1}",
]